/* This file handles signals, which are asynchronous events and are generally
 * a messy and unpleasant business.  Signals can be generated by the KILL
 * system call, or from the keyboard (SIGINT) or from the clock (SIGALRM).
 * In all cases control eventually passes to check_sig() to see which processes
 * can be signaled.  The actual signaling is done by sig_proc().
 *
 * The entry points into this file are:
 *   do_sigaction:	perform the SIGACTION system call
 *   do_sigpending:	perform the SIGPENDING system call
 *   do_sigprocmask:	perform the SIGPROCMASK system call
 *   do_sigreturn:	perform the SIGRETURN system call
 *   do_sigsuspend:	perform the SIGSUSPEND system call
 *   do_kill:		perform the KILL system call
 *   process_ksig:	process a signal an behalf of the kernel
 *   sig_proc:		interrupt or terminate a signaled process
 *   check_sig:		check which processes to signal with sig_proc()
 *   check_pending:	check if a pending signal can now be delivered
 *   restart_sigs: 	restart signal work after finishing a VFS call
 */

#include "pm.h"
#include <sys/stat.h>
#include <sys/ptrace.h>
#include <minix/callnr.h>
#include <minix/endpoint.h>
#include <minix/com.h>
#include <minix/vm.h>
#include <signal.h>
#include <sys/resource.h>
#include <assert.h>
#include "mproc.h"

static int unpause(struct mproc *rmp);
static int sig_send(struct mproc *rmp, int signo);
static void sig_proc_exit(struct mproc *rmp, int signo);

/*===========================================================================*
 *				do_sigaction				     *
 *===========================================================================*/
int do_sigaction(void) {
    int result;
    int signal_number;
    struct sigaction sig_action_vec;
    struct sigaction *sig_action_ptr;

    if (mp->mp_flags & (PROC_STOPPED | VFS_CALL | UNPAUSED | EVENT_CALL)) return(EINVAL);

    signal_number = m_in.m_lc_pm_sig.nr;
    if (signal_number == SIGKILL) return(OK);
    if (signal_number < 1 || signal_number >= _NSIG) return(EINVAL);

    sig_action_ptr = &mp->mp_sigact[signal_number];
    if (m_in.m_lc_pm_sig.oact != NULL) {
        result = sys_datacopy(PM_PROC_NR, (vir_bytes)sig_action_ptr, who_e,
                              m_in.m_lc_pm_sig.oact, sizeof(sig_action_vec));
        if (result != OK) return(result);
    }

    if (m_in.m_lc_pm_sig.act == NULL) return(OK);

    result = sys_datacopy(who_e, m_in.m_lc_pm_sig.act, PM_PROC_NR, (vir_bytes)&sig_action_vec,
                          sizeof(sig_action_vec));
    if (result != OK) return(result);

    switch (sig_action_vec.sa_handler) {
        case SIG_IGN:
            sigaddset(&mp->mp_ignore, signal_number);
            sigdelset(&mp->mp_sigpending, signal_number);
            sigdelset(&mp->mp_ksigpending, signal_number);
            sigdelset(&mp->mp_catch, signal_number);
            break;
        case SIG_DFL:
            sigdelset(&mp->mp_ignore, signal_number);
            sigdelset(&mp->mp_catch, signal_number);
            break;
        default:
            sigdelset(&mp->mp_ignore, signal_number);
            sigaddset(&mp->mp_catch, signal_number);
            break;
    }

    mp->mp_sigact[signal_number].sa_handler = sig_action_vec.sa_handler;
    sigdelset(&sig_action_vec.sa_mask, SIGKILL);
    sigdelset(&sig_action_vec.sa_mask, SIGSTOP);
    mp->mp_sigact[signal_number].sa_mask = sig_action_vec.sa_mask;
    mp->mp_sigact[signal_number].sa_flags = sig_action_vec.sa_flags;
    mp->mp_sigreturn = m_in.m_lc_pm_sig.ret;
    return(OK);
}

/*===========================================================================*
 *				do_sigpending                                *
 *===========================================================================*/
#include <assert.h>

int do_sigpending(void)
{
  if (mp == NULL) return ERROR;

  unsigned int invalid_flags = (PROC_STOPPED | VFS_CALL | UNPAUSED | EVENT_CALL);
  if ((mp->mp_flags & invalid_flags) != 0) return ERROR;

  mp->mp_reply.m_pm_lc_sigset.set = mp->mp_sigpending;

  return OK;
}

/*===========================================================================*
 *				do_sigprocmask                               *
 *===========================================================================*/
#include <assert.h>
#include <errno.h>
#include <signal.h>

int do_sigprocmask(void)
{
    sigset_t set;
    int i;

    if (mp->mp_flags & (PROC_STOPPED | VFS_CALL | UNPAUSED | EVENT_CALL)) {
        return EINVAL;
    }

    set = m_in.m_lc_pm_sigset.set;
    mp->mp_reply.m_pm_lc_sigset.set = mp->mp_sigmask;

    switch (m_in.m_lc_pm_sigset.how) {
        case SIG_BLOCK:
            sigdelset(&set, SIGKILL);
            sigdelset(&set, SIGSTOP);
            for (i = 1; i < _NSIG; i++) {
                if (sigismember(&set, i)) {
                    sigaddset(&mp->mp_sigmask, i);
                }
            }
            break;

        case SIG_UNBLOCK:
            for (i = 1; i < _NSIG; i++) {
                if (sigismember(&set, i)) {
                    sigdelset(&mp->mp_sigmask, i);
                }
            }
            check_pending(mp);
            break;

        case SIG_SETMASK:
            sigdelset(&set, SIGKILL);
            sigdelset(&set, SIGSTOP);
            mp->mp_sigmask = set;
            check_pending(mp);
            break;

        case SIG_INQUIRE:
            break;

        default:
            return EINVAL;
    }
    return OK;
}

/*===========================================================================*
 *				do_sigsuspend                                *
 *===========================================================================*/
#include <assert.h>
#include <signal.h>
#include <errno.h>

// Assume mp and m_in are defined and appropriate types

int do_sigsuspend(void) {
    if (mp->mp_flags & (PROC_STOPPED | VFS_CALL | UNPAUSED | EVENT_CALL)) {
        return -EINVAL; // or appropriate error handling
    }

    mp->mp_sigmask2 = mp->mp_sigmask;
    mp->mp_sigmask = m_in.m_lc_pm_sigset.set;
    sigdelset(&mp->mp_sigmask, SIGKILL);
    sigdelset(&mp->mp_sigmask, SIGSTOP);
    mp->mp_flags |= SIGSUSPENDED;
    check_pending(mp);

    return SUSPEND;
}

/*===========================================================================*
 *				do_sigreturn				     *
 *===========================================================================*/
#include <assert.h>

int do_sigreturn(void) {
    int result;

    if (mp->mp_flags & (PROC_STOPPED | VFS_CALL | UNPAUSED | EVENT_CALL)) {
        return -1; // or appropriate error code
    }

    mp->mp_sigmask = m_in.m_lc_pm_sigset.set;
    sigdelset(&mp->mp_sigmask, SIGKILL);
    sigdelset(&mp->mp_sigmask, SIGSTOP);

    result = sys_sigreturn(who_e, (struct sigmsg *)m_in.m_lc_pm_sigset.ctx);
    check_pending(mp);

    return result;
}

/*===========================================================================*
 *				do_kill					     *
 *===========================================================================*/
int do_kill(void) {
    pid_t pid = m_in.m_lc_pm_sig.pid;
    int signal_nr = m_in.m_lc_pm_sig.nr;

    if (pid < 0 || signal_nr < 1) {
        return -1; // Return error for invalid PID or signal number
    }

    return check_sig(pid, signal_nr, FALSE);
}

/*===========================================================================*
 *			      do_srv_kill				     *
 *===========================================================================*/
#include <errno.h>

int do_srv_kill(void)
{
    if (mp->mp_endpoint != RS_PROC_NR) {
        return EPERM;
    }

    pid_t pid = m_in.m_rs_pm_srv_kill.pid;
    int signo = m_in.m_rs_pm_srv_kill.nr;
    if (pid < 0 || signo <= 0) {
        return EINVAL;
    }
    
    return check_sig(pid, signo, TRUE);
}

/*===========================================================================*
 *				stop_proc				     *
 *===========================================================================*/
static int stop_proc(struct mproc *rmp, int may_delay)
{
    int r = sys_delay_stop(rmp->mp_endpoint);

    if (r == OK) {
        rmp->mp_flags |= PROC_STOPPED;
        return TRUE;
    }

    if (r == EBUSY) {
        if (!may_delay) {
            panic("stop_proc: unexpected delay call");
        }
        rmp->mp_flags |= DELAY_CALL;
        return FALSE;
    }

    panic("sys_delay_stop failed: %d", r);
    return FALSE;  // This line is never reached but ensures a return value
}

/*===========================================================================*
 *				try_resume_proc				     *
 *===========================================================================*/
void try_resume_proc(struct mproc *rmp) {
    if (!(rmp->mp_flags & PROC_STOPPED)) {
        return;
    }

    if (rmp->mp_flags & (VFS_CALL | EVENT_CALL | EXITING)) {
        return;
    }

    int r = sys_resume(rmp->mp_endpoint);
    if (r != OK) {
        panic("sys_resume failed: %d", r);
    }

    rmp->mp_flags &= ~(PROC_STOPPED | UNPAUSED);
}

/*===========================================================================*
 *				process_ksig				     *
 *===========================================================================*/
int process_ksig(endpoint_t proc_nr_e, int signo) {
    int proc_nr;
    if (pm_isokendpt(proc_nr_e, &proc_nr) != OK) {
        return EDEADEPT;
    }

    struct mproc *rmp = &mproc[proc_nr];
    if ((rmp->mp_flags & (IN_USE | EXITING)) != IN_USE) {
        return EDEADEPT;
    }

    pid_t proc_id = rmp->mp_pid;
    mproc[0].mp_procgrp = rmp->mp_procgrp;

    pid_t id;
    switch (signo) {
        case SIGINT:
        case SIGQUIT:
        case SIGWINCH:
        case SIGINFO:
            id = 0;
            break;
        case SIGVTALRM:
        case SIGPROF:
            check_vtimer(proc_nr, signo);
            id = proc_id;
            break;
        default:
            id = proc_id;
            break;
    }

    check_sig(id, signo, TRUE);
    mproc[0].mp_procgrp = 0;

    if (signo == SIGSNDELAY && (rmp->mp_flags & DELAY_CALL)) {
        rmp->mp_flags &= ~DELAY_CALL;

        if (rmp->mp_flags & (VFS_CALL | EVENT_CALL)) {
            stop_proc(rmp, FALSE);
            return OK;
        }

        check_pending(rmp);
    }

    return (mproc[proc_nr].mp_flags & (IN_USE | EXITING)) == IN_USE ? OK : EDEADEPT;
}

/*===========================================================================*
 *				sig_proc				     *
 *===========================================================================*/
void sig_proc(struct mproc *rmp, int signo, int trace, int ksig) {
    int slot = (int) (rmp - mproc);

    if (!(rmp->mp_flags & IN_USE)) {
        panic("PM: signal %d sent to exiting process %d\n", signo, slot);
    }

    if (trace && rmp->mp_tracer != NO_TRACER && signo != SIGKILL) {
        sigaddset(&rmp->mp_sigtrace, signo);

        if (!(rmp->mp_flags & TRACE_STOPPED))
            trace_stop(rmp, signo);

        return;
    }

    if (rmp->mp_flags & (VFS_CALL | EVENT_CALL)) {
        sigaddset(&rmp->mp_sigpending, signo);
        if (ksig)
            sigaddset(&rmp->mp_ksigpending, signo);

        if (!(rmp->mp_flags & (PROC_STOPPED | DELAY_CALL))) {
            stop_proc(rmp, FALSE);
        }
        return;
    }

    if (rmp->mp_flags & PRIV_PROC) {
        if (rmp->mp_endpoint == PM_PROC_NR) {
            return;
        }

        if (!ksig) {
            sys_kill(rmp->mp_endpoint, signo);
            return;
        }

        if (SIGS_IS_STACKTRACE(signo)) {
            sys_diagctl_stacktrace(rmp->mp_endpoint);
        }

        if (!SIGS_IS_TERMINATION(signo)) {
            message m;
            m.m_type = SIGS_SIGNAL_RECEIVED;
            m.m_pm_lsys_sigs_signal.num = signo;
            asynsend3(rmp->mp_endpoint, &m, AMF_NOREPLY);
        } else {
            sig_proc_exit(rmp, signo);
        }
        return;
    }

    if (!ksig && sigismember(&rmp->mp_ignore, signo)) {
        return;
    }

    if (sigismember(&rmp->mp_sigmask, signo)) {
        sigaddset(&rmp->mp_sigpending, signo);
        if (ksig)
            sigaddset(&rmp->mp_ksigpending, signo);
        return;
    }

    if ((rmp->mp_flags & TRACE_STOPPED) && signo != SIGKILL) {
        sigaddset(&rmp->mp_sigpending, signo);
        if (ksig)
            sigaddset(&rmp->mp_ksigpending, signo);
        return;
    }

    if (sigismember(&rmp->mp_catch, signo)) {
        if (!unpause(rmp)) {
            sigaddset(&rmp->mp_sigpending, signo);
            if (ksig)
                sigaddset(&rmp->mp_ksigpending, signo);
            return;
        }

        if (sig_send(rmp, signo)) {
            return;
        }

        printf("PM: %d can't catch signal %d - killing\n", rmp->mp_pid, signo);
    } 

    sig_proc_exit(rmp, signo);
}

/*===========================================================================*
 *				sig_proc_exit				     *
 *===========================================================================*/
static void sig_proc_exit(struct mproc *rmp, int signo) {
    rmp->mp_sigstatus = (char)signo;
    int is_core_signal = sigismember(&core_sset, signo);

    if (is_core_signal && !(rmp->mp_flags & PRIV_PROC)) {
        printf("PM: coredump signal %d for %d / %s\n", signo, rmp->mp_pid, rmp->mp_name);
        sys_diagctl_stacktrace(rmp->mp_endpoint);
    }
    
    exit_proc(rmp, 0, is_core_signal);
}

/*===========================================================================*
 *				check_sig				     *
 *===========================================================================*/
int check_sig(proc_id, signo, ksig)
pid_t proc_id;			/* pid of proc to sig, or 0 or -1, or -pgrp */
int signo;			/* signal to send to process (0 to _NSIG-1) */
int ksig;			/* non-zero means signal comes from kernel  */
{
/* Check to see if it is possible to send a signal.  The signal may have to be
 * sent to a group of processes.  This routine is invoked by the KILL system
 * call, and also when the kernel catches a DEL or other signal.
 */

  register struct mproc *rmp;
  int count;			/* count # of signals sent */
  int error_code;

  if (signo < 0 || signo >= _NSIG) return(EINVAL);

  /* Return EINVAL for attempts to send SIGKILL to INIT alone. */
  if (proc_id == INIT_PID && signo == SIGKILL) return(EINVAL);

  /* Signal RS first when broadcasting SIGTERM. */
  if (proc_id == -1 && signo == SIGTERM)
      sys_kill(RS_PROC_NR, signo);

  /* Search the proc table for processes to signal. Start from the end of the
   * table to analyze core system processes at the end when broadcasting.
   * (See forkexit.c about pid magic.)
   */
  count = 0;
  error_code = ESRCH;
  for (rmp = &mproc[NR_PROCS-1]; rmp >= &mproc[0]; rmp--) {
	if (!(rmp->mp_flags & IN_USE)) continue;

	/* Check for selection. */
	if (proc_id > 0 && proc_id != rmp->mp_pid) continue;
	if (proc_id == 0 && mp->mp_procgrp != rmp->mp_procgrp) continue;
	if (proc_id == -1 && rmp->mp_pid <= INIT_PID) continue;
	if (proc_id < -1 && rmp->mp_procgrp != -proc_id) continue;

	/* Do not kill servers and drivers when broadcasting SIGKILL. */
	if (proc_id == -1 && signo == SIGKILL &&
		(rmp->mp_flags & PRIV_PROC)) continue;

	/* Skip VM entirely as it might lead to a deadlock with its signal
	 * manager if the manager page faults at the same time.
	 */
	if (rmp->mp_endpoint == VM_PROC_NR) continue;

	/* Disallow lethal signals sent by user processes to sys processes. */
	if (!ksig && SIGS_IS_LETHAL(signo) && (rmp->mp_flags & PRIV_PROC)) {
	    error_code = EPERM;
	    continue;
	}

	/* Check for permission. */
	if (mp->mp_effuid != SUPER_USER
	    && mp->mp_realuid != rmp->mp_realuid
	    && mp->mp_effuid != rmp->mp_realuid
	    && mp->mp_realuid != rmp->mp_effuid
	    && mp->mp_effuid != rmp->mp_effuid) {
		error_code = EPERM;
		continue;
	}

	count++;
	if (signo == 0 || (rmp->mp_flags & EXITING)) continue;

	/* 'sig_proc' will handle the disposition of the signal.  The
	 * signal may be caught, blocked, ignored, or cause process
	 * termination, possibly with core dump.
	 */
	sig_proc(rmp, signo, TRUE /*trace*/, ksig);

	if (proc_id > 0) break;	/* only one process being signaled */
  }

  /* If the calling process has killed itself, don't reply. */
  if ((mp->mp_flags & (IN_USE | EXITING)) != IN_USE) return(SUSPEND);
  return(count > 0 ? OK : error_code);
}

/*===========================================================================*
 *				check_pending				     *
 *===========================================================================*/
void check_pending(struct mproc *rmp) {
    int signalNum, ksig;

    for (signalNum = 1; signalNum < _NSIG; signalNum++) {
        if (sigismember(&rmp->mp_sigpending, signalNum) &&
            !sigismember(&rmp->mp_sigmask, signalNum)) {
            
            ksig = sigismember(&rmp->mp_ksigpending, signalNum);
            sigdelset(&rmp->mp_sigpending, signalNum);
            sigdelset(&rmp->mp_ksigpending, signalNum);
            sig_proc(rmp, signalNum, FALSE, ksig);

            if (rmp->mp_flags & (VFS_CALL | EVENT_CALL)) {
                assert(rmp->mp_flags & PROC_STOPPED);
                break;
            }
        }
    }
}

/*===========================================================================*
 *				restart_sigs				     *
 *===========================================================================*/
void restart_sigs(struct mproc *rmp) {
    if ((rmp->mp_flags & (VFS_CALL | EVENT_CALL | EXITING)) != 0) {
        return;
    }

    if ((rmp->mp_flags & TRACE_EXIT) != 0) {
        exit_proc(rmp, rmp->mp_exitstatus, FALSE);
        return;
    }

    if ((rmp->mp_flags & PROC_STOPPED) != 0) {
        assert((rmp->mp_flags & DELAY_CALL) == 0);
        check_pending(rmp);
        try_resume_proc(rmp);
    }
}

/*===========================================================================*
 *				unpause					     *
 *===========================================================================*/
static int unpause(struct mproc *rmp) {
    message m;

    if (rmp->mp_flags & UNPAUSED) {
        assert((rmp->mp_flags & (DELAY_CALL | PROC_STOPPED)) == PROC_STOPPED);
        return TRUE;
    }

    if (rmp->mp_flags & DELAY_CALL) {
        return FALSE;
    }

    if (rmp->mp_flags & (WAITING | SIGSUSPENDED)) {
        stop_proc(rmp, FALSE);
        return TRUE;
    }

    if (!(rmp->mp_flags & PROC_STOPPED) && !stop_proc(rmp, TRUE)) {
        return FALSE;
    }

    memset(&m, 0, sizeof(m));
    m.m_type = VFS_PM_UNPAUSE;
    m.VFS_PM_ENDPT = rmp->mp_endpoint;

    tell_vfs(rmp, &m);

    return FALSE;
}

/*===========================================================================*
 *				sig_send				     *
 *===========================================================================*/
static int sig_send(struct mproc *rmp, int signo) {
    if (!(rmp->mp_flags & PROC_STOPPED)) {
        return FALSE;
    }

    struct sigmsg sigmsg;
    sigmsg.sm_signo = signo;
    sigmsg.sm_sighandler = (vir_bytes)rmp->mp_sigact[signo].sa_handler;
    sigmsg.sm_sigreturn = rmp->mp_sigreturn;

    int sigflags = rmp->mp_sigact[signo].sa_flags;
    sigmsg.sm_mask = (rmp->mp_flags & SIGSUSPENDED) ? rmp->mp_sigmask2 : rmp->mp_sigmask;
    
    for (int i = 1; i < _NSIG; i++) {
        if (sigismember(&rmp->mp_sigact[signo].sa_mask, i)) {
            sigaddset(&rmp->mp_sigmask, i);
        }
    }

    if (sigflags & SA_NODEFER) {
        sigdelset(&rmp->mp_sigmask, signo);
    } else {
        sigaddset(&rmp->mp_sigmask, signo);
    }

    if (sigflags & SA_RESETHAND) {
        sigdelset(&rmp->mp_catch, signo);
        rmp->mp_sigact[signo].sa_handler = SIG_DFL;
    }

    sigdelset(&rmp->mp_sigpending, signo);
    sigdelset(&rmp->mp_ksigpending, signo);

    int r = sys_sigsend(rmp->mp_endpoint, &sigmsg);
    if (r == EFAULT || r == ENOMEM) {
        return FALSE;
    }

    if (r != OK) {
        panic("sys_sigsend failed: %d", r);
    }

    if (rmp->mp_flags & (WAITING | SIGSUSPENDED)) {
        rmp->mp_flags &= ~(WAITING | SIGSUSPENDED);
        reply((int)(rmp - mproc), EINTR);

        assert(!(rmp->mp_flags & UNPAUSED));
        try_resume_proc(rmp);
        assert(!(rmp->mp_flags & PROC_STOPPED));
    } else {
        assert(rmp->mp_flags & UNPAUSED);
    }

    return TRUE;
}
